<#
.SYNOPSIS
    Auto-generated installation script for Unknown App
    Generated by AI Automation Script Generator
    Platform: PowerShell (Native)
#>

$InstallerPath = "C:\Users\RajeshKodaganti(Quad\Downloads\GITHUB\DEMO-3\ai_automation_script_gen\dummy_setup.exe"
$InstallCmd = '"C:\Users\RajeshKodaganti(Quad\Downloads\GITHUB\DEMO-3\ai_automation_script_gen\dummy_setup.exe" /S'

Write-Host "Checking installer existence at: $InstallerPath"
if (-not (Test-Path $InstallerPath)) {
    Write-Error "CRITICAL: Installer not found at $InstallerPath"
    exit 1
}

Write-Host "Starting silent installation command: $InstallCmd"

try {
    $time = Measure-Command {
        # Run process and wait
        $proc = Start-Process -FilePath "cmd.exe" -ArgumentList "/c $InstallCmd" -PassThru -Wait -NoNewWindow
    }
    
    Write-Host "Command executed in $($time.TotalSeconds) seconds."
    Write-Host "Return Code: $($proc.ExitCode)"
    
    if ($proc.ExitCode -eq 0) {
        Write-Host "PASS: Installation process completed successfully." -ForegroundColor Green
        exit 0
    } else {
        Write-Host "FAIL: Installation process returned non-zero code." -ForegroundColor Red
        exit $proc.ExitCode
    }
} catch {
    Write-Error "FAIL: execution failed: $_"
    exit 1
}
