import os

class ScriptGenerator:
    def __init__(self, analysis_result):
        self.analysis = analysis_result
    
    def generate_script(self):
        # Default to raw path if no command introspection worked
        path = self.analysis.get("path", "")
        install_cmd = self.analysis.get("install_cmd", f'"{path}"')
        product_name = self.analysis.get("properties", {}).get("ProductName", "Unknown App")
        
        # PowerShell Script Template
        script_content = f'''<#
.SYNOPSIS
    Auto-generated installation script for {product_name}
    Generated by AI Automation Script Generator
    Platform: PowerShell (Native)
#>

$InstallerPath = "{path}"
$InstallCmd = '{install_cmd}'

Write-Host "Checking installer existence at: $InstallerPath"
if (-not (Test-Path $InstallerPath)) {{
    Write-Error "CRITICAL: Installer not found at $InstallerPath"
    exit 1
}}

Write-Host "Starting silent installation command: $InstallCmd"

try {{
    $time = Measure-Command {{
        # Run process and wait
        $proc = Start-Process -FilePath "cmd.exe" -ArgumentList "/c $InstallCmd" -PassThru -Wait -NoNewWindow
    }}
    
    Write-Host "Command executed in $($time.TotalSeconds) seconds."
    Write-Host "Return Code: $($proc.ExitCode)"
    
    if ($proc.ExitCode -eq 0) {{
        Write-Host "PASS: Installation process completed successfully." -ForegroundColor Green
        exit 0
    }} else {{
        Write-Host "FAIL: Installation process returned non-zero code." -ForegroundColor Red
        exit $proc.ExitCode
    }}
}} catch {{
    Write-Error "FAIL: execution failed: $_"
    exit 1
}}
'''
        return script_content

    def generate_gui_script(self, events):
        """
        Generates a PowerShell script using UIAutomation.
        """
        path = self.analysis.get("path", "")
        
        header = """
Add-Type -AssemblyName UIAutomationClient
Add-Type -AssemblyName UIAutomationTypes

function Find-Click($name) {
    param($root)
    $cond = New-Object System.Windows.Automation.PropertyCondition([System.Windows.Automation.AutomationElement]::NameProperty, $name)
    $element = $root.FindFirst([System.Windows.Automation.TreeScope]::Descendants, $cond)
    if ($element) {
        $invoke = $element.GetCurrentPattern([System.Windows.Automation.InvokePattern]::Pattern)
        $invoke.Invoke()
        Write-Host "Clicked $name"
    }
}
"""
        steps_code = []
        for event in events:
            if 'action' in event and event['action'] == 'click':
                title = event['selector']['title']
                steps_code.append(f'Find-Click -name "{title}" -root $root')
                steps_code.append('Start-Sleep -Seconds 2')

        steps_joined = "\n".join(steps_code)

        script_content = f'''{header}

$InstallerPath = "{path}"
Write-Host "Launching GUI installer: $InstallerPath"

$proc = Start-Process -FilePath $InstallerPath -PassThru
Start-Sleep -Seconds 3

try {{
    $root = [System.Windows.Automation.AutomationElement]::FromHandle($proc.MainWindowHandle)
    if (-not $root) {{ throw "Could not attach to window" }}

    {steps_joined}
    
    Write-Host "Installation sequence finished."
}} catch {{
    Write-Error "GUI Automation failed: $_"
}}
'''
        return script_content
