import os

class ScriptGenerator:
    def __init__(self, analysis_result):
        self.analysis = analysis_result
    
    def generate_python_script(self):
        # Default to raw path if no command introspection worked
        path = self.analysis.get("path", "")
        install_cmd = self.analysis.get("install_cmd", f'"{path}"')
        product_name = self.analysis.get("properties", {}).get("ProductName", "Unknown App")
        
        script_content = f'''import os
import subprocess
import time
import sys

def install():
    """
    Auto-generated installation script for {product_name}
    Generated by AI Automation Script Generator
    """
    installer_path = r"{path}"
    install_cmd = r'{install_cmd}'
    
    print(f"Checking installer existence at: {{installer_path}}")
    if not os.path.exists(installer_path):
        print(f"CRITICAL: Installer not found at {{installer_path}}")
        return False

    print(f"Starting silent installation command: {{install_cmd}}")
    
    try:
        # execute installation
        # Shell=True allows using command line arguments easily
        start_time = time.time()
        process = subprocess.run(install_cmd, shell=True, check=True, timeout=600, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        duration = time.time() - start_time
        
        print(f"Command executed in {{duration:.2f}} seconds.")
        print(f"Return Code: {{process.returncode}}")
        
        if process.stdout:
            print(f"Output: {{process.stdout.decode('utf-8', errors='ignore')}}")
        
        if process.returncode == 0:
            print("PASS: Installation process completed successfully.")
            return True
        else:
            print(f"FAIL: Installation process returned non-zero code.")
            return False
            
    except subprocess.CalledProcessError as e:
        print(f"FAIL: Installation failed with return code {{e.returncode}}")
        if e.stderr:
             print(f"Error Output: {{e.stderr.decode('utf-8', errors='ignore')}}")
        return False
    except subprocess.TimeoutExpired:
        print("FAIL: Installation timed out after 600 seconds.")
        return False
    except Exception as e:
        print(f"FAIL: An unexpected error occurred: {{e}}")
        return False

    def generate_gui_script(self, events):
        """
        Generates a pywinauto script based on recorded events/decisions.
        events: list of dicts from LLMClient.decide_next_action
        """
        path = self.analysis.get("path", "").replace("\\", "\\\\")
        
        steps_code = []
        for event in events:
            # We assume event has 'code' key pre-generated or we generate it here
            # For this MVP, let's assume raw code strings in 'code' or reconstruction
            if 'code_snippet' in event:
                steps_code.append(f"    # {event.get('reason', 'Action')}")
                steps_code.append(f"    try:")
                steps_code.append(f"        {event['code_snippet']}")
                steps_code.append(f"        time.sleep(1) # wait for reaction")
                steps_code.append(f"    except Exception as e: print(f'Step failed: {{e}}')")
                steps_code.append(f"")

        steps_joined = "\n".join(steps_code)

        script_content = f'''from pywinauto import Application
import time
import sys
import os

def install_gui():
    installer_path = r"{path}"
    print(f"Launching GUI installer: {{installer_path}}")
    
    try:
        app = Application(backend="uia").start(installer_path)
        time.sleep(3) # Initial load wait
        
        # Connect to window - simplifying assumption of finding top window
        dlg = app.top_window()
        
{steps_joined}
        
        print("Installation sequence finished.")
        return True
        
    except Exception as e:
        print(f"GUI Automation failed: {{e}}")
        return False

if __name__ == "__main__":
    install_gui()
'''
        return script_content

if __name__ == "__main__":
    if install():
        sys.exit(0)
    else:
        sys.exit(1)
'''
        return script_content
